version: "3.7"

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  internal:
    driver: bridge

services:
  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - internal

  app:
    build: .docker/app
    links:
      - db
    volumes:
      - ./volumes/nextcloud:/var/www/html
    restart: always
    networks:
      - internal

  web:
    container_name: web
    build: .docker/web
    restart: always
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=mydomain.coop
      - LETSENCRYPT_HOST=mydomain.coop
      #- LETSENCRYPT_EMAIL=user@mydomain.coop
    depends_on:
      - app
    networks:
      - internal
      - reverse-proxy