version: "3.7"

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  onlyoffice:
    external: true
    name: onlyoffice
  postgres:
    external: true
    name: postgres
  redis:
    external: true
    name: redis
  internal:
    driver: bridge

services:
  app:
    build: .docker/app
    volumes:
      - ./volumes/nextcloud:/var/www/html
    restart: always
    environment:
      - TZ
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - REDIS_HOST
      - NEXTCLOUD_TRUSTED_DOMAINS
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_PORT
      - SMTP_AUTHTYPE
      - SMTP_NAME
      - SMTP_PASSWORD
      - MAIL_FROM_ADDRESS
      - MAIL_DOMAIN
    networks:
      - internal
      - postgres
      - onlyoffice
      - redis
  web:
    container_name: web
    build: .docker/web
    restart: always
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
      - ./volumes/nginx/includes:/etc/nginx/conf.d/includes/
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - TZ
    depends_on:
      - app
    networks:
      - internal
      - reverse-proxy
      - onlyoffice 
  cron:
    build: .docker/app
    restart: unless-stopped
    volumes:
      - ./volumes/nextcloud:/var/www/html
      - ./volumes/cron/cronfile:/var/spool/cron/crontabs/www-data
    networks:
      - internal
      - postgres
      - redis
    environment:
      - TZ
    entrypoint: /cron.sh
