version: "3.7"

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  internal:
    driver: bridge

services:
  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - internal

  app:
    build: .docker/app
    links:
      - db
    volumes:
      - ./volumes/nextcloud:/var/www/html
    environment:
      - POSTGRES_DB=db
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-SECRET_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-admin}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-mydomain.coop}    
    env_file:
      - .env  
    restart: always
    networks:
      - internal

  web:
    container_name: web
    build: .docker/web
    restart: always
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=mydomain.coop
      - LETSENCRYPT_HOST=mydomain.coop
      #- LETSENCRYPT_EMAIL=user@mydomain.coop
    depends_on:
      - app
    networks:
      - internal
      - reverse-proxy
      
  cron:
    build: .docker/app
    restart: unless-stopped
    volumes:
      - ./volumes/nextcloud:/var/www/html
    networks:
      - internal
    entrypoint: /cron.sh

  #documentserver:
  #  image: onlyoffice/documentserver
  #  restart: always
  #  environment:
  #    - VIRTUAL_HOST=onlyoffice.mydomain.coop
  #    - LETSENCRYPT_HOST=onlyoffice.mydomain.coop
  #  volumes:
  #    - ./volumes/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
  #    - ./volumes/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data
  #  networks:
  #    - internal
  #    - reverse-proxy
