networks:
  internal:
    driver: bridge

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    restart: always
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}
      - POSTGRES_PASSWORD
    networks:
      - internal

