services:
  onlyoffice:
    image: onlyoffice/documentserver
    restart: always
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_ONLYOFFICE}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_ONLYOFFICE}
    volumes:
      - ./volumes/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
      - ./volumes/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data
    networks:
      - internal
      - reverse-proxy
