networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  internal:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal

  app:
    build:
      context: .docker/app
      args:
        NEXTCLOUD_VERSION: ${NEXTCLOUD_VERSION:-stable-fpm}
    volumes:
      - ./volumes/nextcloud:/var/www/html
      - ./backups:/backups
      - ./app-hooks/pre-installation:/docker-entrypoint-hooks.d/pre-installation
      - ./app-hooks/post-installation:/docker-entrypoint-hooks.d/post-installation
      - ./app-hooks/pre-upgrade:/docker-entrypoint-hooks.d/pre-upgrade
      - ./app-hooks/post-upgrade:/docker-entrypoint-hooks.d/post-upgrade
      - ./app-hooks/before-starting:/docker-entrypoint-hooks.d/before-starting
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_ADMIN_EMAIL
      - NEXTCLOUD_TRUSTED_DOMAINS
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_PORT
      - SMTP_AUTHTYPE
      - SMTP_NAME
      - SMTP_PASSWORD
      - MAIL_FROM_ADDRESS
      - MAIL_DOMAIN
      - TZ
    depends_on:
      - redis
    networks:
      - internal

  web:
    build: .docker/web
    restart: unless-stopped
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
      - ./volumes/nginx/includes:/etc/nginx/conf.d/includes:rw
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - TZ
    depends_on:
      - app
    networks:
      - internal
      - reverse-proxy

  cron:
    build:
      context: .docker/app
      args:
        NEXTCLOUD_VERSION: ${NEXTCLOUD_VERSION:-stable-fpm}
    restart: unless-stopped
    environment:
      - TZ
    volumes:
      - ./volumes/nextcloud:/var/www/html
    depends_on:
      - redis
    networks:
      - internal
    entrypoint: /cron.sh
