networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  postgres:
    external: true
    name: postgres
  internal:
    driver: bridge

services:
  app:
    build:
      context: .docker/app
      args:
        NEXTCLOUD_VERSION: ${NEXTCLOUD_VERSION:-stable-fpm}
    volumes:
      - ./volumes/nextcloud:/var/www/html
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_PORT
      - SMTP_AUTHTYPE
      - SMTP_NAME
      - SMTP_PASSWORD
      - MAIL_FROM_ADDRESS
      - MAIL_DOMAIN
      - TZ
    networks:
      - postgres
      - internal

  web:
    build: .docker/web
    restart: unless-stopped
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
      - ./volumes/nginx/includes:/etc/nginx/conf.d/includes:rw
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    depends_on:
      - app
    networks:
      - internal
      - reverse-proxy

  cron:
    build: .docker/app
    restart: unless-stopped
    volumes:
      - ./volumes/nextcloud:/var/www/html
    networks:
      - postgres
      - internal
    entrypoint: /cron.sh
