version: "3.7"

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  internal:
    driver: bridge

services:
  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    networks:
      - internal

  app:
    build: .docker/app
    links:
      - db
    volumes:
      - ./volumes/nextcloud:/var/www/html
    restart: always
    environment:
      - TZ
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - REDIS_HOST
      - NEXTCLOUD_TRUSTED_DOMAINS
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_PORT
      - SMTP_AUTHTYPE
      - SMTP_NAME
      - SMTP_PASSWORD
      - MAIL_FROM_ADDRESS
      - MAIL_DOMAIN
    networks:
      - internal

  web:
    container_name: web
    build: .docker/web
    restart: always
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
      - ./volumes/nginx/includes:/etc/nginx/conf.d/includes:rw
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    depends_on:
      - app
    networks:
      - internal
      - reverse-proxy
      
  cron:
    build: .docker/app
    restart: unless-stopped
    volumes:
      - ./volumes/nextcloud:/var/www/html
    networks:
      - internal
    entrypoint: /cron.sh

  #documentserver:
  #  image: onlyoffice/documentserver
  #  restart: always
  #  environment:
  #    - VIRTUAL_HOST=${VIRTUAL_HOST_ONLYOFFICE}
  #    - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_ONLYOFFICE}
  #  volumes:
  #    - ./volumes/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
  #    - ./volumes/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data
  #  networks:
  #    - internal
  #    - reverse-proxy
