version: "3.7"

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  internal:
    driver: bridge

services:
  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - internal

  app:
    build: .docker/app
    links:
      - db
    volumes:
      - ./volumes/nextcloud:/var/www/html
      - .docker/web/timeout.conf:/etc/nginx/conf.d/timeout.conf
    restart: always
    networks:
      - internal

  web:
    container_name: web
    build: .docker/web
    restart: always
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=mydomain.coop
      - LETSENCRYPT_HOST=mydomain.coop
      #- LETSENCRYPT_EMAIL=user@mydomain.coop
    depends_on:
      - app
    networks:
      - internal
      - reverse-proxy
      
  cron:
    image: nextcloud:stable-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./volumes/nextcloud:/var/www/html
    networks:
      - internal
    entrypoint: /cron.sh

  #documentserver:
  #  image: onlyoffice/documentserver
  #  restart: always
  #  environment:
  #    - VIRTUAL_HOST=onlyoffice.mydomain.coop
  #    - LETSENCRYPT_HOST=onlyoffice.mydomain.coop
  #  volumes:
  #    - ./volumes/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
  #    - ./volumes/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data
  #  networks:
  #    - internal
  #    - reverse-proxy
