name: Build and Push Docker Image
on:
  push:
    branches:
      - add-actions
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker APP image
      run: docker build -t ghcr.io/librecodecoop/nextcloud-app:31-fpm-latest -f .docker/app/Dockerfile .
      
    - name: Build Docker WEB image
      run: docker build -t ghcr.io/librecodecoop/nextcloud-web:31-fpm-latest -f .docker/web/Dockerfile .


    - name: Push Docker APP image
      run: docker push ghcr.io/librecodecoop/nextcloud-app:31-fpm-latest

    - name: Push Docker WEB image
      run: docker push ghcr.io/librecodecoop/nextcloud-web:31-fpm-latest
